spring.application.name=briefin-be

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=briefin-secret-key-must-be-at-least-32-characters-long-enough
jwt.access-token-expiration=3600000