spring.application.name=briefin-be

spring.datasource.url=jdbc:postgresql://localhost:5432/briefin
spring.datasource.username=postgres
spring.datasource.password=1381
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:briefin-secret-key-briefin-secret-key-2026}
jwt.access-token-expiration=3600000